### ISSUE TITLE
Question about HW #2 and FASTA format

### ISSUE THREAD

**Issue by tjp36** [uchicago-bio/2016-Autumn-Forum#4]
Is there a way to tell from the description of a FASTA sequence whether the sequence is a DNA sequence, RNA, or a protein sequence?  Furthermore, does our parser need to determine what type of sequence we are dealing with (DNA, RNA, protein) or can we assume that we know the type of sequence located in the file?

Does our parser need to handle the case where symbols for one type of sequence are inappropriately placed in another?  For example, an 'E' character (glutamate) placed in a DNA sequence.  

Thanks

**Comment by tabinks** [comment]
> Is there a way to tell from the description of a FASTA sequence whether the sequence is a DNA sequence, RNA, or a protein sequence? 

No.  In many cases the header line will give some clues based on the sequence id, but there is no uniform (and agreed upon way).

> Furthermore, does our parser need to determine what type of sequence we are dealing with (DNA, RNA, protein) or can we assume that we know the type of sequence located in the file?

You can handle this different ways.  One scenario would be you pass a flag (eg. --dna/--rna) into you program.  Alternatively, you could just detect it from the sequence. _Hint: Look for the presence of a `U`_.  The tricky part will be to distinguish between a dna and protein sequence, since there are amino acids CGTA.  In this case, you would want to look for the presence of any of the other amino acid letter codes.

Does our parser need to handle the case where symbols for one type of sequence are inappropriately placed in another? For example, an 'E' character (glutamate) placed in a DNA sequence.

Yes, incorrect characters should be handled.  This is a very prevalent problem in bioinformatics.   The most common (but not universal) way is to either remove or replace by appropriate letter codes (e.g., N for unknown nucleic acid residue or X for unknown amino acid residue).  In terms of a sequence database, this allows the portion of the sequence that is known to be stored.  However, if terms of analysis it can break many software programs that don't know how to handle a bad character.

**For this assignment, if you encounter a bad character, you can break out of the parsing and report it to the user.**

For example, `"In sequence [print out header here], there was a unknown character [character here] at position [sequence position]."`  In my opinion, this is the best way to handle these error, as trying to analyze a sequence with bad information will only propagate errors.  Also, it provides the opportunity to fix the error.

Thanks
